### ISSUE TITLE
[QUESTION] Quadtree for pathfinding?

### ISSUE THREAD

**Issue by xDGameStudios** [CodingTrain/QuadTree#48]
Hi, not really a bug here!
I'm kinda into pathfinding right now and trying to get good ways of improve performance of it...
well I know A* is largely used everywhere and I know how to use it. But I've only used it with grids... what about (nav)meshes or quad-trees? Is this possible? Could someone provide some guidance?

BTW: I don't know if there is a request section on CodeTraining :P but I wanted to know how could one implement such a thing... maybe quad-trees would be a simpler challenge to start with as creating meshes (even from a bunch of straight rectangles combined + holes in it would be extremely complex).

**Comment by crhallberg** [comment]
Hello!

QuadTrees and A* can certainly be used together! First, let's break these two technologies down.

A* is a search algorithm that's good for finding the optimal path or choices given a search space (like a maze).

A QuadTree is a storage system that makes it easy to find items inside a given area. This is great if you want to check for collisions or find nearby objects to where you are!

You'd do well to apply them together to a problem where you are searching through a spatial area (instead of [finding the best move in a game](https://xkcd.com/832/), for example) and the next step isn't fixed.

For example, on a grid, the next step is fixed because you either go up, down, left, or right from where you are. If instead, the available steps were the 5 closest berries or if you were trying to avoid a collision, these mini-searches for the next step could be sped up enormously by using a QuadTree and the larger search could be managed by an A* search.

To conjure an example, if you wanted to find the fastest way across a room avoiding some collidable objects, you could use these two to take a step in a random direction (A*) and see if you've hit anything (QuadTree) and score each step on how close it gets you to the exit (A*). [Here is a similar but more complex, real-world example](https://caseymuratori.com/blog_0005).

I hope that helps clear it up! I'll be here for followup questions!
